name: "Test Python Prod"

concurrency: "1"

on:
  push:
    branches:
      - master

jobs:
  destroy:
    name: "Destroy Production Jobs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle destroy  --auto-approve --target prod
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
  deploy:
    name: "Deploy to Prod"
    runs-on: ubuntu-latest

    needs:
      - destroy

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy --target prod
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
  pipeline_update:
    name: "Run Update pipeline"
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: nohup databricks bundle run my_project_job_1 &
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod